# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T10_DHy8ll5Ft3IayQPmngJThgylZeFj
"""



!pip install pandas

import pandas as pd
df=pd.read_csv("/content/Zomato-data-.csv")

display(df.tail())

display(df.head())

df.columns

df

df.shape

df.info

df.isnull().sum()

pip install matplotlib

pip install seaborn

import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x='online_order',data=df,color='green')

sns.barplot(x='online_order',y='votes',data=df,color='blue')

sns.scatterplot(x='votes',y='rate',data=df,color='orange')

df['rate']

df[['rate','votes']]

df_cleaned = df.copy()
df_cleaned['rate'] = df_cleaned['rate'].str.replace('/5', '', regex=False)
df_cleaned['rate'] = pd.to_numeric(df_cleaned['rate'], errors='coerce')
df_cleaned[['rate','votes']].corr()

corr=df_cleaned[['rate','votes']].corr()
sns.heatmap(corr,annot=True)

pip install scikit-learn

from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['listed_in(type)']=le.fit_transform(df['listed_in(type)'])

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['name']=le.fit_transform(df['name'])

df

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df['listed_in(type)']=oe.fit_transform(df[['listed_in(type)']])

df

#df['votes']=df['votes'].fillna(df['votes'].mode()(0))
#df['votes']=df['votes'].fillna(df['votes'].mean()(0))

df.describe()

#df['listed_in(type)']=df['listed_in(type)'].fillna(df['listed_in(type)'].mode()(0))

df.describe()

